# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_talk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': 'palestra', 'verbose_name_plural': 'palestras'},
        ),
        migrations.RemoveField(
            model_name='talk',
            name='speakers',
        ),
        migrations.AddField(
            model_name='talk',
            name='palestrantes',
            field=models.ManyToManyField(to='core.Speaker'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description',
            field=models.TextField(verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='start',
            field=models.TimeField(verbose_name='início'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
