# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160212_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='palestrantes',
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(to='core.Speaker', verbose_name='palestrantes'),
        ),
    ]
